### ISSUE TITLE
 Alterar o nome "repository" da Classe que se comunica com a API

### ISSUE THREAD

**Issue by LeonnardoVerol** [Infnet-SJ90/desktop-app#14]
Classe: [PedidoDeAgendamentoRepository.ts](https://github.com/Infnet-SJ90/desktop-app/blob/7d9330cc4d0f9cf15ff9d1190db7e5094ff31659/src/PedidoDeAgendamentoRepository.ts)

Opcoes:
- NomeDaClasseInterface
- NomeDaClasseAPI
- etc

**Comment by calebesantos** [comment]
Alterar o nome "repository" da Classe que se comunica com a API
